site_name: Universal_hal
plugins:
  - mkdoxy:
      projects:
        atmelsam/: # name of project must be alphanumeric + numbers (without spaces)
          src-dirs: "hal/ hal/platform/atmelsam/"
          full-doc: True
          doxy-cfg:
            FILE_PATTERNS: "*.c *.h*"
            RECURSIVE: False
            EXTRACT_ALL: True
markdown_extensions:
  - toc
  - tables
  - admonition
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true 
  - pymdownx.details
  - pymdownx.blocks.admonition:
      types:
      - new
      - settings
      - note
      - abstract
      - info
      - tip
      - success
      - question
      - warning
      - failure
      - danger
      - bug
      - example
      - quote
theme: material
features:
  - content.tabs.link
nav:
  - Home: "index.md"
  - API:
      - SAMD:
        - "Structs":
          - "Struct List": "atmelsam/annotated.md"
          - "Struct Member Variables": "atmelsam/class_member_variables.md"
        - "Functions": "atmelsam/functions.md"
        - "Variables": "atmelsam/variables.md"
        - "Macros": "atmelsam/macros.md"
        - "Files": "atmelsam/files.md"
  - Contributing:
    - 'General': 'contributing.md'
    - 'Code style': 'code_style.md'

