#ifndef UART_PLATFORM_SPECIFIC_H
#define UART_PLATFORM_SPECIFIC_H

typedef enum {
    UART_PERIPHERAL_0,
    UART_PERIPHERAL_1,
    UART_PERIPHERAL_2,
    UART_PERIPHERAL_3,
    UART_PERIPHERAL_4,
    UART_PERIPHERAL_5
} uart_inst_t;

typedef enum {
    SPI_BUS_OPT_USE_DEFAULT = 0,
    SPI_BUS_OPT_CLOCK_POLARITY_SCK_HIGH = 0x01,
    SPI_BUS_OPT_DATA_ORDER_LSB_FIRST = 0x02,
    SPI_BUS_OPT_CHAR_SIZE_10_BIT = 0x04,
    SPI_BUS_OPT_DOPO_PAD_0 = 0x08,
    SPI_BUS_OPT_DOPO_PAD_1 = 0x10,
    SPI_BUS_OPT_DOPO_PAD_2 = 0x18,
    SPI_BUS_OPT_DOPO_PAD_3 = 0x20,
    SPI_BUS_OPT_DIPO_PAD_0 = 0x40,
    SPI_BUS_OPT_DIPO_PAD_1 = 0x80,
    SPI_BUS_OPT_DIPO_PAD_2 = 0xC0,
    SPI_BUS_OPT_DIPO_PAD_3 = 0x100
} uart_opt_t;


#endif // UART_PLATFORM_SPECIFIC_H
