name: ci
on:
  push:
    branches:
      - stable
      - main
permissions:
  contents: write
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: threeal/cmake-action@v1.3.0
      - runs: cmake -DUHAL_BUILD_TESTS=1 . -B build  && cd build && make -j2
      - runs: ctest --test-dir build
