name: run tests
on:
  push:
    branches:
      - stable
      - main
permissions:
  contents: write
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4.1.1

      - name: Build Project
        run: cmake -DUHAL_BUILD_TESTS=1 . -B build  && cd build && make -j2

      - name: Test Project
        run: ctest --test-dir build
